branches:
  only:
  - master

env:
  global:
  - RGL_USE_NULL=TRUE

language: r
sudo: required
cache: packages
warnings_are_errors: true

cran: http://cran.rstudio.com
r_build_args: "--no-manual"
r_check_args: "--no-build-vignettes --no-manual"

r:
  - release
  - devel

addons:
  apt:
    packages:
      - libgit2-dev

r_packages:
  - devtools
  - sessioninfo
  - covr
  - data.table
  - delayed
  - origami
  - hal9001
  - mma

r_github_packages:
  - tlverse/sl3
  - tlverse/tmle3
  - nhejazi/medshift

after_success:
  ## coverage
  - travis_wait 80 Rscript -e 'covr::codecov()'

on_failure:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
    on_failure: change
